"""add iv_at_open to trades

Revision ID: 6f16456426f8
Revises: ff1efbb4cc30
Create Date: 2026-03-07 01:28:14.485171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f16456426f8'
down_revision: Union[str, None] = 'ff1efbb4cc30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('iv_at_open', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'iv_at_open')
    # ### end Alembic commands ###
