"""initial schema

Revision ID: bb016ed931ff
Revises: 
Create Date: 2026-03-06 13:43:39.170478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb016ed931ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('asset_type', sa.Enum('STOCK', 'ETF', name='assettype'), nullable=True),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expense_ratio', sa.Numeric(), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(), nullable=True),
    sa.Column('beta', sa.Numeric(), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_symbol'), 'spot', ['symbol'], unique=True)
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_id', sa.Integer(), nullable=False),
    sa.Column('strategy_type', sa.Enum('CSP', 'CC', name='strategytype'), nullable=False),
    sa.Column('strike', sa.Numeric(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('total_premium', sa.Numeric(), nullable=False),
    sa.Column('commission', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'ASSIGNED', 'ROLLED', name='tradestatus'), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=False),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('closing_cost', sa.Numeric(), nullable=True),
    sa.Column('closing_spot', sa.Numeric(), nullable=True),
    sa.Column('spot_price_at_open', sa.Numeric(), nullable=True),
    sa.Column('broker_trade_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['underlying_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_trade_id')
    )
    op.create_index(op.f('ix_trade_opened_at'), 'trade', ['opened_at'], unique=False)
    op.create_index(op.f('ix_trade_underlying_id'), 'trade', ['underlying_id'], unique=False)
    op.create_table('sharelot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('underlying_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('cost_per_share', sa.Numeric(), nullable=False),
    sa.Column('acquired_at', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('ASSIGNMENT', 'MANUAL_BUY', 'TRANSFER', name='lotsource'), nullable=False),
    sa.Column('linked_trade_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_trade_id'], ['trade.id'], ),
    sa.ForeignKeyConstraint(['underlying_id'], ['spot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sharelot_underlying_id'), 'sharelot', ['underlying_id'], unique=False)
    op.create_table('tradeevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('OPEN', 'CLOSE', 'ASSIGNMENT', 'EXERCISE', 'ROLL_OPEN', 'ROLL_CLOSE', 'ADJUSTMENT', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('fees', sa.Numeric(), nullable=False),
    sa.Column('linked_event_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['linked_event_id'], ['tradeevent.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tradeevent_trade_id'), 'tradeevent', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tradeevent_trade_id'), table_name='tradeevent')
    op.drop_table('tradeevent')
    op.drop_index(op.f('ix_sharelot_underlying_id'), table_name='sharelot')
    op.drop_table('sharelot')
    op.drop_index(op.f('ix_trade_underlying_id'), table_name='trade')
    op.drop_index(op.f('ix_trade_opened_at'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_spot_symbol'), table_name='spot')
    op.drop_table('spot')
    # ### end Alembic commands ###
